# Site settings
title: Turpial Development
tagline: "New cool site"
url: "http://turpialdev.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
instagram: turpialdev

# Contact
phone: "916-276-1044" # This is my real number. You should text me.
email: "hello@turpialdev.com" # This is my real email address. Please don't email me.

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

navigation:
  - section: Home
    url: '/index/'

  - section: Blog
    url: '/blog/'

  - section: Services
    url: '/index/#web'
    subsection:

      - section: Web
        url: '/index/#web'

      - section: Mobile
        url: '/index/#mobile'

      - section: Design
        url: '/index/#design'

  - section: Portfolio
    url: '/index/#portfolio'

  - section: About Us
    url: '/index/#aboutus'

  - section: Advantages
    url: '/index/#advantage'

  - section: Contact
    url: '/index/#contact'


collections:
  portfolio:
    output: true
  sections:
    output: false
  opportunities:
    output: true
  team:
    output: false
