# Site settings
title: Turpial Development
tagline: "New cool site"
url: "http://turpialdev.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: "/img/logo-turpial.png" # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
instagram: turpialdev

# Contact
phone: "916-276-1044"
email: "hello@turpialdev.com"

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

navigation:
  - section: Home
    url: '/'
    target: '_self"'

  - section: Blog
    url: 'https://medium.com/turpialdev'
    target: '_blank"'

  - section: Services
    url: '/#web'
    target: '_self"'
    subsection:

      - section: Web
        url: '/#web'
        target: '_self"'

      - section: Mobile
        url: '/#mobile'
        target: '_self"'

      - section: Design
        url: '/#design'
        target: '_self"'

  - section: Portfolio
    url: '/#portfolio'
    target: '_self"'

  - section: About Us
    url: '/#aboutus'
    target: '_self"'

  - section: Advantages
    url: '/#advantage'
    target: '_self"'

  - section: Contact
    url: '/#contact'
    target: '_self"'


collections:
  portfolio:
    output: true
  sections:
    output: false
  opportunities:
    output: true
  team:
    output: false
